[package]
name = "hddm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[dependencies]
anyhow.workspace = true
clap.workspace = true
flate2.workspace = true
gluex-core.workspace = true
md5.workspace = true
quick-xml.workspace = true
thiserror.workspace = true

hddm-derive = { workspace = true, optional = true }

[features]
default = ['derive']
derive = ['dep:hddm-derive']
