use std::io::Write;

use crate::{ElementReader, HddmPrimitiveRead, HddmPrimitiveWrite, HddmResult, HddmWriter};

#[allow(non_camel_case_types)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Particle {
    UnknownParticle,
    Gamma,
    Positron,
    Electron,
    Neutrino,
    MuonPlus,
    MuonMinus,
    Pi0,
    PiPlus,
    PiMinus,
    KLong,
    KPlus,
    KMinus,
    Neutron,
    Proton,
    AntiProton,
    KShort,
    Eta,
    Lambda,
    SigmaPlus,
    Sigma0,
    SigmaMinus,
    Xi0,
    XiMinus,
    OmegaMinus,
    AntiNeutron,
    AntiLambda,
    AntiSigmaMinus,
    AntiSigma0,
    AntiSigmaPlus,
    AntiXi0,
    AntiXiPlus,
    AntiOmegaPlus,
    omega,
    phiMeson,
    EtaPrime,
    RhoPlus,
    RhoMinus,
    Rho0,
    Deuteron,
    Triton,
    Helium,
    Geantino,
    He3,
    GammaOptical,
    Li6,
    Li7,
    Be7,
    Be9,
    B10,
    B11,
    C12,
    N14,
    O16,
    F19,
    Ne20,
    Na23,
    Mg24,
    Al27,
    Si28,
    P31,
    S32,
    Cl35,
    Ar36,
    K39,
    Ca40,
    Sc45,
    Ti48,
    V51,
    Cr52,
    Mn55,
    Fe56,
    Co59,
    Ni58,
    Cu63,
    Zn64,
    Ge74,
    Se80,
    Kr84,
    Sr88,
    Zr90,
    Mo98,
    Pd106,
    Cd114,
    Sn120,
    Xe132,
    Ba138,
    Ce140,
    Sm152,
    Dy164,
    Yb174,
    W184,
    Pt194,
    Au197,
    Hg202,
    Pb208,
    U238,
    Ta181,
    a0_980,
    f0_980,
    KStar_892_0,
    KStar_892_Plus,
    KStar_892_Minus,
    AntiKStar_892_0,
    K1_1400_Plus,
    K1_1400_Minus,
    b1_1235_Plus,
    Sigma_1385_Minus,
    Sigma_1385_0,
    Sigma_1385_Plus,
    DeltaPlusPlus,
    Jpsi,
    Eta_c,
    Chi_c0,
    Chi_c1,
    Chi_c2,
    Psi2s,
    D0,
    DPlus,
    Dstar0,
    DstarPlus,
    Lambda_c,
    AntiD0,
    DMinus,
    DstarMinus,
    Sigma_cPlusPlus,
}

impl From<&Particle> for i32 {
    fn from(value: &Particle) -> Self {
        (*value).into()
    }
}

impl From<i32> for Particle {
    fn from(value: i32) -> Self {
        match value {
            0 => Self::UnknownParticle,
            1 => Self::Gamma,
            2 => Self::Positron,
            3 => Self::Electron,
            4 => Self::Neutrino,
            5 => Self::MuonPlus,
            6 => Self::MuonMinus,
            7 => Self::Pi0,
            8 => Self::PiPlus,
            9 => Self::PiMinus,
            10 => Self::KLong,
            11 => Self::KPlus,
            12 => Self::KMinus,
            13 => Self::Neutron,
            14 => Self::Proton,
            15 => Self::AntiProton,
            16 => Self::KShort,
            17 => Self::Eta,
            18 => Self::Lambda,
            19 => Self::SigmaPlus,
            20 => Self::Sigma0,
            21 => Self::SigmaMinus,
            22 => Self::Xi0,
            23 => Self::XiMinus,
            24 => Self::OmegaMinus,
            25 => Self::AntiNeutron,
            26 => Self::AntiLambda,
            27 => Self::AntiSigmaMinus,
            28 => Self::AntiSigma0,
            29 => Self::AntiSigmaPlus,
            30 => Self::AntiXi0,
            31 => Self::AntiXiPlus,
            32 => Self::AntiOmegaPlus,
            33 => Self::omega,
            34 => Self::phiMeson,
            35 => Self::EtaPrime,
            42 => Self::RhoPlus,
            43 => Self::RhoMinus,
            44 => Self::Rho0,
            45 => Self::Deuteron,
            46 => Self::Triton,
            47 => Self::Helium,
            48 => Self::Geantino,
            49 => Self::He3,
            50 => Self::GammaOptical,
            61 => Self::Li6,
            62 => Self::Li7,
            63 => Self::Be7,
            64 => Self::Be9,
            65 => Self::B10,
            66 => Self::B11,
            67 => Self::C12,
            68 => Self::N14,
            69 => Self::O16,
            70 => Self::F19,
            71 => Self::Ne20,
            72 => Self::Na23,
            73 => Self::Mg24,
            74 => Self::Al27,
            75 => Self::Si28,
            76 => Self::P31,
            77 => Self::S32,
            78 => Self::Cl35,
            79 => Self::Ar36,
            80 => Self::K39,
            81 => Self::Ca40,
            82 => Self::Sc45,
            83 => Self::Ti48,
            84 => Self::V51,
            85 => Self::Cr52,
            86 => Self::Mn55,
            87 => Self::Fe56,
            88 => Self::Co59,
            89 => Self::Ni58,
            90 => Self::Cu63,
            91 => Self::Zn64,
            92 => Self::Ge74,
            93 => Self::Se80,
            94 => Self::Kr84,
            95 => Self::Sr88,
            96 => Self::Zr90,
            97 => Self::Mo98,
            98 => Self::Pd106,
            99 => Self::Cd114,
            100 => Self::Sn120,
            101 => Self::Xe132,
            102 => Self::Ba138,
            103 => Self::Ce140,
            104 => Self::Sm152,
            105 => Self::Dy164,
            106 => Self::Yb174,
            107 => Self::W184,
            108 => Self::Pt194,
            109 => Self::Au197,
            110 => Self::Hg202,
            111 => Self::Pb208,
            112 => Self::U238,
            113 => Self::Ta181,
            163 => Self::a0_980,
            164 => Self::f0_980,
            165 => Self::KStar_892_0,
            166 => Self::KStar_892_Plus,
            167 => Self::KStar_892_Minus,
            168 => Self::AntiKStar_892_0,
            169 => Self::K1_1400_Plus,
            170 => Self::K1_1400_Minus,
            171 => Self::b1_1235_Plus,
            172 => Self::Sigma_1385_Minus,
            173 => Self::Sigma_1385_0,
            174 => Self::Sigma_1385_Plus,
            182 => Self::DeltaPlusPlus,
            183 => Self::Jpsi,
            184 => Self::Eta_c,
            185 => Self::Chi_c0,
            186 => Self::Chi_c1,
            187 => Self::Chi_c2,
            188 => Self::Psi2s,
            189 => Self::D0,
            190 => Self::DPlus,
            191 => Self::Dstar0,
            192 => Self::DstarPlus,
            193 => Self::Lambda_c,
            194 => Self::AntiD0,
            195 => Self::DMinus,
            196 => Self::DstarMinus,
            197 => Self::Sigma_cPlusPlus,
            _ => Particle::UnknownParticle,
        }
    }
}

impl From<&i32> for Particle {
    fn from(value: &i32) -> Self {
        (*value).into()
    }
}

impl From<Particle> for i32 {
    fn from(value: Particle) -> Self {
        match value {
            Particle::UnknownParticle => 0,
            Particle::Gamma => 1,
            Particle::Positron => 2,
            Particle::Electron => 3,
            Particle::Neutrino => 4,
            Particle::MuonPlus => 5,
            Particle::MuonMinus => 6,
            Particle::Pi0 => 7,
            Particle::PiPlus => 8,
            Particle::PiMinus => 9,
            Particle::KLong => 10,
            Particle::KPlus => 11,
            Particle::KMinus => 12,
            Particle::Neutron => 13,
            Particle::Proton => 14,
            Particle::AntiProton => 15,
            Particle::KShort => 16,
            Particle::Eta => 17,
            Particle::Lambda => 18,
            Particle::SigmaPlus => 19,
            Particle::Sigma0 => 20,
            Particle::SigmaMinus => 21,
            Particle::Xi0 => 22,
            Particle::XiMinus => 23,
            Particle::OmegaMinus => 24,
            Particle::AntiNeutron => 25,
            Particle::AntiLambda => 26,
            Particle::AntiSigmaMinus => 27,
            Particle::AntiSigma0 => 28,
            Particle::AntiSigmaPlus => 29,
            Particle::AntiXi0 => 30,
            Particle::AntiXiPlus => 31,
            Particle::AntiOmegaPlus => 32,
            Particle::omega => 33,
            Particle::phiMeson => 34,
            Particle::EtaPrime => 35,
            Particle::RhoPlus => 42,
            Particle::RhoMinus => 43,
            Particle::Rho0 => 44,
            Particle::Deuteron => 45,
            Particle::Triton => 46,
            Particle::Helium => 47,
            Particle::Geantino => 48,
            Particle::He3 => 49,
            Particle::GammaOptical => 50,
            Particle::Li6 => 61,
            Particle::Li7 => 62,
            Particle::Be7 => 63,
            Particle::Be9 => 64,
            Particle::B10 => 65,
            Particle::B11 => 66,
            Particle::C12 => 67,
            Particle::N14 => 68,
            Particle::O16 => 69,
            Particle::F19 => 70,
            Particle::Ne20 => 71,
            Particle::Na23 => 72,
            Particle::Mg24 => 73,
            Particle::Al27 => 74,
            Particle::Si28 => 75,
            Particle::P31 => 76,
            Particle::S32 => 77,
            Particle::Cl35 => 78,
            Particle::Ar36 => 79,
            Particle::K39 => 80,
            Particle::Ca40 => 81,
            Particle::Sc45 => 82,
            Particle::Ti48 => 83,
            Particle::V51 => 84,
            Particle::Cr52 => 85,
            Particle::Mn55 => 86,
            Particle::Fe56 => 87,
            Particle::Co59 => 88,
            Particle::Ni58 => 89,
            Particle::Cu63 => 90,
            Particle::Zn64 => 91,
            Particle::Ge74 => 92,
            Particle::Se80 => 93,
            Particle::Kr84 => 94,
            Particle::Sr88 => 95,
            Particle::Zr90 => 96,
            Particle::Mo98 => 97,
            Particle::Pd106 => 98,
            Particle::Cd114 => 99,
            Particle::Sn120 => 100,
            Particle::Xe132 => 101,
            Particle::Ba138 => 102,
            Particle::Ce140 => 103,
            Particle::Sm152 => 104,
            Particle::Dy164 => 105,
            Particle::Yb174 => 106,
            Particle::W184 => 107,
            Particle::Pt194 => 108,
            Particle::Au197 => 109,
            Particle::Hg202 => 110,
            Particle::Pb208 => 111,
            Particle::U238 => 112,
            Particle::Ta181 => 113,
            Particle::a0_980 => 163,
            Particle::f0_980 => 164,
            Particle::KStar_892_0 => 165,
            Particle::KStar_892_Plus => 166,
            Particle::KStar_892_Minus => 167,
            Particle::AntiKStar_892_0 => 168,
            Particle::K1_1400_Plus => 169,
            Particle::K1_1400_Minus => 170,
            Particle::b1_1235_Plus => 171,
            Particle::Sigma_1385_Minus => 172,
            Particle::Sigma_1385_0 => 173,
            Particle::Sigma_1385_Plus => 174,
            Particle::DeltaPlusPlus => 182,
            Particle::Jpsi => 183,
            Particle::Eta_c => 184,
            Particle::Chi_c0 => 185,
            Particle::Chi_c1 => 186,
            Particle::Chi_c2 => 187,
            Particle::Psi2s => 188,
            Particle::D0 => 189,
            Particle::DPlus => 190,
            Particle::Dstar0 => 191,
            Particle::DstarPlus => 192,
            Particle::Lambda_c => 193,
            Particle::AntiD0 => 194,
            Particle::DMinus => 195,
            Particle::DstarMinus => 196,
            Particle::Sigma_cPlusPlus => 197,
        }
    }
}

impl HddmPrimitiveRead for Particle {
    fn read_primitive(r: &mut ElementReader) -> HddmResult<Self> {
        Ok(r.read_i32()?.into())
    }
}

impl HddmPrimitiveWrite for Particle {
    fn write_primitive<W: Write>(&self, w: &mut HddmWriter<W>) -> HddmResult<()> {
        w.write_i32(self.into())
    }
}
